openapi: 3.0.1
info:
  title: My API
  version: 1.0.0
paths:
  /bash-hello-world:
    post:
      responses: { }
  /bash-hello-target-body-text:
    post:
      parameters:
        - name: target
          description: The plain text body containing the target to say hello to.
          required: true
          schema:
            type: string
      responses: { }
  /csharp-script-hello-world:
    get:
      responses: { }
  /bash-hello-target:
    get:
      parameters:
        - name: target
          description: The target to say hello to.
          required: true
          schema:
            type: string
      responses: { }
  /csharp-hello-world:
    get:
      responses: { }
  /file-create:
    post:
      parameters:
        - name: workingDirectory
          description: The base path where the file will be created.
          required: true
          schema:
            type: string
        - name: filePath
          description: The path of the file relative to the working directory.
          required: true
          schema:
            type: string
        - name: content
          description: The content to write to the file.
          required: true
          schema:
            type: string
      responses: { }
  /bash-hello-target-body-json:
    post:
      parameters:
        - name: target
          description: The JSON body containing the target to say hello to.
          required: true
          schema:
            type: json
      responses: { }
  /endpoint-list:
    get:
      responses: { }