---
openapi: 3.0.1
info:
  title: DynamicAPI Self-Evolving Endpoints
  description: DynamicAPI is a self-evolving API service that allows for the dynamic generation of endpoints from JSON files. With the ability to create, list, and execute endpoints, DynamicAPI provides a flexible and efficient solution for expanding API functionality. Leveraging the power of ChatGPT, DynamicAPI aims to streamline the process of endpoint creation, making API development faster and more efficient.
  version: 'v1'
servers:
  - url: https://dynamicapi.madebyaibots.com
paths:
  /endpoint-list:
    get:
      operationId: endpointList
      summary: A list of all endpoints
      description: This endpoint returns a list of all endpoints.
      responses:
        "200":
          description: The request was successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  endpoints:
                    type: array
                    items:
                      type: string
                    description: The list of endpoints.
