@startuml
[Program] as P
[EndpointService] as ES
[RequestProcessor] as RP
[EndpointExecutor] as EE
P --> ES : Creates
P --> RP : Creates
P --> EE : Creates
RP --> EE : Uses
@enduml

View Diagram: https://showme.redstarplugin.com/d/VIsAcUdJ