name: Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Print working directory before checkout
        run: pwd
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Execute build script
        run: bash ./build.sh




  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory before checkout
        run: pwd
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Auth Token
        run: bash ./generate-auth-token.sh
      - name: Execute test script
        run: bash ./test.sh

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run install.sh script
        run: sudo bash ./install.sh

      - name: Verify Installation
        run: |
          # Commands to verify the dotnet API is running with systemd
          systemctl status dynamicapi
