name: Build and Test

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Print working directory before checkout
        run: pwd
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Execute build script
        run: bash ./build.sh

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory before checkout
        run: pwd
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate Auth Token
        run: bash ./generate-auth-token.sh
        
      - name: Build
        run: bash build.sh
        
      - name: Execute test script
        run: bash ./test.sh

  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: bash build.sh
        
      - name: Run and Test
        run: bash run-and-test.sh
        
  install:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run publish.sh
        run: bash publish.sh
        
      - name: Run prepare.sh script
        run: sudo bash prepare.sh
        
      - name: Run install.sh script
        run: sudo bash install.sh
        
      - name: Check Service Status
        run: systemctl status dynamicapi || true

      - name: Output Service Logs
        run: journalctl -u dynamicapi
        
  install-from-source:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run install-from-source.sh script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./curl-scripts/install-from-source.sh

  graduate:
    needs: [test, install, run]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Set authenticated URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Configure Git pull strategy
        run: git config pull.rebase false

      - name: List all branches
        run: git branch -a

      - name: Install gitpython module
        run: pip install gitpython

      - name: Get branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Configure Git pull strategy
        run: git config pull.rebase false

      - name: Run graduate.py
        run: python3 graduate.py --branch=${{ env.BRANCH_NAME }}

